/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * Prompt Forge API - version 0.0.0
 *
 *
 *
 * OpenAPI version: 3.0.0
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'ModelSettings.get_api_providers': ['GET', '/api/providers'],
  'ModelSettings.post_api_providers_openai_compatible': ['POST', '/api/providers/openai-compatible'],
  'ModelSettings.put_api_providers_provider_id': ['PUT', '/api/providers/{providerId}'],
  'ModelSettings.post_api_providers_provider_id_models_sync': ['POST', '/api/providers/{providerId}/models/sync'],
  'ModelSettings.post_api_models': ['POST', '/api/models'],
  'ModelSettings.put_api_models_model_id': ['PUT', '/api/models/{modelId}'],
  'ModelSettings.get_api_model_defaults': ['GET', '/api/model-defaults'],
  'ModelSettings.put_api_model_defaults': ['PUT', '/api/model-defaults'],
  'PromptRuntime.post_api_prompt_evaluate': ['POST', '/api/prompt/evaluate'],
  'PromptRuntime.post_api_prompt_optimize': ['POST', '/api/prompt/optimize']
};
