/* tslint:disable */
/* eslint-disable */
/**
 * Prompt Forge API - version 0.0.0
 *
 *
 *
 * OpenAPI version: 3.0.0
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
import type { Alova, AlovaMethodCreateConfig, AlovaGenerics, Method } from 'alova';
import type { $$userConfigMap, alovaInstance } from './index';
import type apiDefinitions from './apiDefinitions';

type CollapsedAlova = typeof alovaInstance;
type UserMethodConfigMap = typeof $$userConfigMap;

type Alova2MethodConfig<Responded> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Omit<
        AlovaMethodCreateConfig<
          AlovaGenerics<Responded, any, RequestConfig, Response, ResponseHeader, L1Cache, L2Cache, SE>,
          any,
          Responded
        >,
        'params'
      >
    : never;

// Extract the return type of transform function that define in $$userConfigMap, if it not exists, use the default type.
type ExtractUserDefinedTransformed<
  DefinitionKey extends keyof typeof apiDefinitions,
  Default
> = DefinitionKey extends keyof UserMethodConfigMap
  ? UserMethodConfigMap[DefinitionKey]['transform'] extends (...args: any[]) => any
    ? Awaited<ReturnType<UserMethodConfigMap[DefinitionKey]['transform']>>
    : Default
  : Default;
type Alova2Method<
  Responded,
  DefinitionKey extends keyof typeof apiDefinitions,
  CurrentConfig extends Alova2MethodConfig<any>
> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Method<
        AlovaGenerics<
          CurrentConfig extends undefined
            ? ExtractUserDefinedTransformed<DefinitionKey, Responded>
            : CurrentConfig['transform'] extends (...args: any[]) => any
              ? Awaited<ReturnType<CurrentConfig['transform']>>
              : ExtractUserDefinedTransformed<DefinitionKey, Responded>,
          any,
          RequestConfig,
          Response,
          ResponseHeader,
          L1Cache,
          L2Cache,
          SE
        >
      >
    : never;

declare global {
  interface Apis {
    ModelSettings: {
      /**
       * ---
       *
       * [GET]
       *
       * **path:** /api/providers
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   success: true
       *   data: {
       *     // [items] start
       *     // [items] end
       *     providers: Array<{
       *       id: string
       *       kind: 'openai' | 'openai-compatible'
       *       code: string
       *       name: string
       *       baseUrl: string
       *       enabled: boolean
       *       hasApiKey: boolean
       *       apiKeyMasked: string | null
       *       // [items] start
       *       // [items] end
       *       models: Array<{
       *         id: string
       *         providerId: string
       *         modelName: string
       *         displayName: string | null
       *         enabled: boolean
       *         source: 'sync' | 'manual'
       *         lastSyncedAt: string | null
       *       }>
       *     }>
       *   }
       *   requestId?: string
       * }
       * ```
       */
      get_api_providers<
        Config extends Alova2MethodConfig<{
          success: true;
          data: {
            providers: Array<{
              id: string;
              kind: 'openai' | 'openai-compatible';
              code: string;
              name: string;
              baseUrl: string;
              enabled: boolean;
              hasApiKey: boolean;
              apiKeyMasked: string | null;
              models: Array<{
                id: string;
                providerId: string;
                modelName: string;
                displayName: string | null;
                enabled: boolean;
                source: 'sync' | 'manual';
                lastSyncedAt: string | null;
              }>;
            }>;
          };
          requestId?: string;
        }>
      >(
        config?: Config
      ): Alova2Method<
        {
          success: true;
          data: {
            providers: Array<{
              id: string;
              kind: 'openai' | 'openai-compatible';
              code: string;
              name: string;
              baseUrl: string;
              enabled: boolean;
              hasApiKey: boolean;
              apiKeyMasked: string | null;
              models: Array<{
                id: string;
                providerId: string;
                modelName: string;
                displayName: string | null;
                enabled: boolean;
                source: 'sync' | 'manual';
                lastSyncedAt: string | null;
              }>;
            }>;
          };
          requestId?: string;
        },
        'ModelSettings.get_api_providers',
        Config
      >;
      /**
       * ---
       *
       * [POST]
       *
       * **path:** /api/providers/openai-compatible
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   name: string
       *   baseUrl: string
       *   apiKey?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   success: true
       *   data: {
       *     providerId: string
       *   }
       *   requestId?: string
       * }
       * ```
       */
      post_api_providers_openai_compatible<
        Config extends Alova2MethodConfig<{
          success: true;
          data: {
            providerId: string;
          };
          requestId?: string;
        }> & {
          data: {
            name: string;
            baseUrl: string;
            apiKey?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<
        {
          success: true;
          data: {
            providerId: string;
          };
          requestId?: string;
        },
        'ModelSettings.post_api_providers_openai_compatible',
        Config
      >;
      /**
       * ---
       *
       * [PUT]
       *
       * **path:** /api/providers/{providerId}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   providerId: string
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   name?: string
       *   baseUrl?: string
       *   enabled?: boolean
       *   apiKey?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   success: true
       *   data: {
       *     provider: {
       *       id: string
       *       kind: 'openai' | 'openai-compatible'
       *       code: string
       *       name: string
       *       baseUrl: string
       *       enabled: boolean
       *       hasApiKey: boolean
       *       apiKeyMasked: string | null
       *     }
       *   }
       *   requestId?: string
       * }
       * ```
       */
      put_api_providers_provider_id<
        Config extends Alova2MethodConfig<{
          success: true;
          data: {
            provider: {
              id: string;
              kind: 'openai' | 'openai-compatible';
              code: string;
              name: string;
              baseUrl: string;
              enabled: boolean;
              hasApiKey: boolean;
              apiKeyMasked: string | null;
            };
          };
          requestId?: string;
        }> & {
          pathParams: {
            providerId: string;
          };
          data: {
            name?: string;
            baseUrl?: string;
            enabled?: boolean;
            apiKey?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<
        {
          success: true;
          data: {
            provider: {
              id: string;
              kind: 'openai' | 'openai-compatible';
              code: string;
              name: string;
              baseUrl: string;
              enabled: boolean;
              hasApiKey: boolean;
              apiKeyMasked: string | null;
            };
          };
          requestId?: string;
        },
        'ModelSettings.put_api_providers_provider_id',
        Config
      >;
      /**
       * ---
       *
       * [POST]
       *
       * **path:** /api/providers/{providerId}/models/sync
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   providerId: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   success: true
       *   data: {
       *     providerId: string
       *     inserted: number
       *     updated: number
       *     total: number
       *   }
       *   requestId?: string
       * }
       * ```
       */
      post_api_providers_provider_id_models_sync<
        Config extends Alova2MethodConfig<{
          success: true;
          data: {
            providerId: string;
            inserted: number;
            updated: number;
            total: number;
          };
          requestId?: string;
        }> & {
          pathParams: {
            providerId: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<
        {
          success: true;
          data: {
            providerId: string;
            inserted: number;
            updated: number;
            total: number;
          };
          requestId?: string;
        },
        'ModelSettings.post_api_providers_provider_id_models_sync',
        Config
      >;
      /**
       * ---
       *
       * [POST]
       *
       * **path:** /api/models
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   providerId: string
       *   modelName: string
       *   displayName?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   success: true
       *   data: {
       *     modelId: string
       *   }
       *   requestId?: string
       * }
       * ```
       */
      post_api_models<
        Config extends Alova2MethodConfig<{
          success: true;
          data: {
            modelId: string;
          };
          requestId?: string;
        }> & {
          data: {
            providerId: string;
            modelName: string;
            displayName?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<
        {
          success: true;
          data: {
            modelId: string;
          };
          requestId?: string;
        },
        'ModelSettings.post_api_models',
        Config
      >;
      /**
       * ---
       *
       * [PUT]
       *
       * **path:** /api/models/{modelId}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   modelId: string
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   displayName?: string | null
       *   enabled?: boolean
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   success: true
       *   data: {
       *     model: {
       *       id: string
       *       providerId: string
       *       modelName: string
       *       displayName: string | null
       *       enabled: boolean
       *       source: 'sync' | 'manual'
       *       lastSyncedAt: string | null
       *     }
       *   }
       *   requestId?: string
       * }
       * ```
       */
      put_api_models_model_id<
        Config extends Alova2MethodConfig<{
          success: true;
          data: {
            model: {
              id: string;
              providerId: string;
              modelName: string;
              displayName: string | null;
              enabled: boolean;
              source: 'sync' | 'manual';
              lastSyncedAt: string | null;
            };
          };
          requestId?: string;
        }> & {
          pathParams: {
            modelId: string;
          };
          data: {
            displayName?: string | null;
            enabled?: boolean;
          };
        }
      >(
        config: Config
      ): Alova2Method<
        {
          success: true;
          data: {
            model: {
              id: string;
              providerId: string;
              modelName: string;
              displayName: string | null;
              enabled: boolean;
              source: 'sync' | 'manual';
              lastSyncedAt: string | null;
            };
          };
          requestId?: string;
        },
        'ModelSettings.put_api_models_model_id',
        Config
      >;
      /**
       * ---
       *
       * [GET]
       *
       * **path:** /api/model-defaults
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   success: true
       *   data: {
       *     evaluateModelId: string | null
       *     optimizeModelId: string | null
       *   }
       *   requestId?: string
       * }
       * ```
       */
      get_api_model_defaults<
        Config extends Alova2MethodConfig<{
          success: true;
          data: {
            evaluateModelId: string | null;
            optimizeModelId: string | null;
          };
          requestId?: string;
        }>
      >(
        config?: Config
      ): Alova2Method<
        {
          success: true;
          data: {
            evaluateModelId: string | null;
            optimizeModelId: string | null;
          };
          requestId?: string;
        },
        'ModelSettings.get_api_model_defaults',
        Config
      >;
      /**
       * ---
       *
       * [PUT]
       *
       * **path:** /api/model-defaults
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   evaluateModelId?: string | null
       *   optimizeModelId?: string | null
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   success: true
       *   data: {
       *     evaluateModelId: string | null
       *     optimizeModelId: string | null
       *   }
       *   requestId?: string
       * }
       * ```
       */
      put_api_model_defaults<
        Config extends Alova2MethodConfig<{
          success: true;
          data: {
            evaluateModelId: string | null;
            optimizeModelId: string | null;
          };
          requestId?: string;
        }> & {
          data: {
            evaluateModelId?: string | null;
            optimizeModelId?: string | null;
          };
        }
      >(
        config: Config
      ): Alova2Method<
        {
          success: true;
          data: {
            evaluateModelId: string | null;
            optimizeModelId: string | null;
          };
          requestId?: string;
        },
        'ModelSettings.put_api_model_defaults',
        Config
      >;
    };
    PromptRuntime: {
      /**
       * ---
       *
       * [POST]
       *
       * **path:** /api/prompt/evaluate
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   prompt: string
       *   modelId?: string
       *   temperature?: number
       *   maxTokens?: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   success: true
       *   data: {
       *     evaluationResult: string
       *     resolvedModel: {
       *       providerId: string
       *       providerKind: 'openai' | 'openai-compatible'
       *       modelId: string
       *       modelName: string
       *     }
       *   }
       *   requestId?: string
       * }
       * ```
       */
      post_api_prompt_evaluate<
        Config extends Alova2MethodConfig<{
          success: true;
          data: {
            evaluationResult: string;
            resolvedModel: {
              providerId: string;
              providerKind: 'openai' | 'openai-compatible';
              modelId: string;
              modelName: string;
            };
          };
          requestId?: string;
        }> & {
          data: {
            prompt: string;
            modelId?: string;
            temperature?: number;
            maxTokens?: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<
        {
          success: true;
          data: {
            evaluationResult: string;
            resolvedModel: {
              providerId: string;
              providerKind: 'openai' | 'openai-compatible';
              modelId: string;
              modelName: string;
            };
          };
          requestId?: string;
        },
        'PromptRuntime.post_api_prompt_evaluate',
        Config
      >;
      /**
       * ---
       *
       * [POST]
       *
       * **path:** /api/prompt/optimize
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   prompt: string
       *   evaluationResult?: string
       *   modelId?: string
       *   temperature?: number
       *   maxTokens?: number
       *   evaluateContext?: {
       *     modelId: string
       *     temperature?: number
       *     maxTokens?: number
       *   }
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   success: true
       *   data: {
       *     optimizedPrompt: string
       *     resolvedModel: {
       *       providerId: string
       *       providerKind: 'openai' | 'openai-compatible'
       *       modelId: string
       *       modelName: string
       *     }
       *     promptRunId: string
       *     savedPromptId: string
       *     persistence: {
       *       saved: boolean
       *       retryable: boolean
       *       saveDraft?: {
       *         version: 'v1'
       *         issuedAt: string
       *         expiresAt: string
       *         payload: {
       *           promptRunId: string
       *           savedPromptId: string
       *           originalPrompt: string
       *           evaluationResult: string | null
       *           optimizedPrompt: string
       *           evaluateModelId: string | null
       *           optimizeModelId: string
       *           evaluateParams: {
       *             temperature?: number
       *             maxTokens?: number
       *           } | null
       *           optimizeParams: {
       *             temperature?: number
       *             maxTokens?: number
       *           } | null
       *           createdAt: string
       *         }
       *         signature: string
       *       }
       *     }
       *   }
       *   requestId?: string
       * }
       * ```
       */
      post_api_prompt_optimize<
        Config extends Alova2MethodConfig<{
          success: true;
          data: {
            optimizedPrompt: string;
            resolvedModel: {
              providerId: string;
              providerKind: 'openai' | 'openai-compatible';
              modelId: string;
              modelName: string;
            };
            promptRunId: string;
            savedPromptId: string;
            persistence: {
              saved: boolean;
              retryable: boolean;
              saveDraft?: {
                version: 'v1';
                issuedAt: string;
                expiresAt: string;
                payload: {
                  promptRunId: string;
                  savedPromptId: string;
                  originalPrompt: string;
                  evaluationResult: string | null;
                  optimizedPrompt: string;
                  evaluateModelId: string | null;
                  optimizeModelId: string;
                  evaluateParams: {
                    temperature?: number;
                    maxTokens?: number;
                  } | null;
                  optimizeParams: {
                    temperature?: number;
                    maxTokens?: number;
                  } | null;
                  createdAt: string;
                };
                signature: string;
              };
            };
          };
          requestId?: string;
        }> & {
          data: {
            prompt: string;
            evaluationResult?: string;
            modelId?: string;
            temperature?: number;
            maxTokens?: number;
            evaluateContext?: {
              modelId: string;
              temperature?: number;
              maxTokens?: number;
            };
          };
        }
      >(
        config: Config
      ): Alova2Method<
        {
          success: true;
          data: {
            optimizedPrompt: string;
            resolvedModel: {
              providerId: string;
              providerKind: 'openai' | 'openai-compatible';
              modelId: string;
              modelName: string;
            };
            promptRunId: string;
            savedPromptId: string;
            persistence: {
              saved: boolean;
              retryable: boolean;
              saveDraft?: {
                version: 'v1';
                issuedAt: string;
                expiresAt: string;
                payload: {
                  promptRunId: string;
                  savedPromptId: string;
                  originalPrompt: string;
                  evaluationResult: string | null;
                  optimizedPrompt: string;
                  evaluateModelId: string | null;
                  optimizeModelId: string;
                  evaluateParams: {
                    temperature?: number;
                    maxTokens?: number;
                  } | null;
                  optimizeParams: {
                    temperature?: number;
                    maxTokens?: number;
                  } | null;
                  createdAt: string;
                };
                signature: string;
              };
            };
          };
          requestId?: string;
        },
        'PromptRuntime.post_api_prompt_optimize',
        Config
      >;
    };
    SavedPrompts: {
      /**
       * ---
       *
       * [GET]
       *
       * **path:** /api/saved-prompts
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   limit?: number
       *   cursor?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   success: true
       *   data: {
       *     // [items] start
       *     // [items] end
       *     items: Array<{
       *       id: string
       *       promptRunId: string
       *       optimizedPrompt: string
       *       createdAt: string
       *     }>
       *     nextCursor: string | null
       *   }
       *   requestId?: string
       * }
       * ```
       */
      get_api_saved_prompts<
        Config extends Alova2MethodConfig<{
          success: true;
          data: {
            items: Array<{
              id: string;
              promptRunId: string;
              optimizedPrompt: string;
              createdAt: string;
            }>;
            nextCursor: string | null;
          };
          requestId?: string;
        }> & {
          params: {
            limit?: number;
            cursor?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<
        {
          success: true;
          data: {
            items: Array<{
              id: string;
              promptRunId: string;
              optimizedPrompt: string;
              createdAt: string;
            }>;
            nextCursor: string | null;
          };
          requestId?: string;
        },
        'SavedPrompts.get_api_saved_prompts',
        Config
      >;
      /**
       * ---
       *
       * [POST]
       *
       * **path:** /api/saved-prompts/retry
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   saveDraft: {
       *     version: 'v1'
       *     issuedAt: string
       *     expiresAt: string
       *     payload: {
       *       promptRunId: string
       *       savedPromptId: string
       *       originalPrompt: string
       *       evaluationResult: string | null
       *       optimizedPrompt: string
       *       evaluateModelId: string | null
       *       optimizeModelId: string
       *       evaluateParams: {
       *         temperature?: number
       *         maxTokens?: number
       *       } | null
       *       optimizeParams: {
       *         temperature?: number
       *         maxTokens?: number
       *       } | null
       *       createdAt: string
       *     }
       *     signature: string
       *   }
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   success: true
       *   data: {
       *     promptRunId: string
       *     savedPromptId: string
       *     saved: true
       *   }
       *   requestId?: string
       * }
       * ```
       */
      post_api_saved_prompts_retry<
        Config extends Alova2MethodConfig<{
          success: true;
          data: {
            promptRunId: string;
            savedPromptId: string;
            saved: true;
          };
          requestId?: string;
        }> & {
          data: {
            saveDraft: {
              version: 'v1';
              issuedAt: string;
              expiresAt: string;
              payload: {
                promptRunId: string;
                savedPromptId: string;
                originalPrompt: string;
                evaluationResult: string | null;
                optimizedPrompt: string;
                evaluateModelId: string | null;
                optimizeModelId: string;
                evaluateParams: {
                  temperature?: number;
                  maxTokens?: number;
                } | null;
                optimizeParams: {
                  temperature?: number;
                  maxTokens?: number;
                } | null;
                createdAt: string;
              };
              signature: string;
            };
          };
        }
      >(
        config: Config
      ): Alova2Method<
        {
          success: true;
          data: {
            promptRunId: string;
            savedPromptId: string;
            saved: true;
          };
          requestId?: string;
        },
        'SavedPrompts.post_api_saved_prompts_retry',
        Config
      >;
    };
  }

  var Apis: Apis;
}
